palette = "pop_default"
add_newline = false
format = "$all"

[palettes.pop_default]
base = "#1d2021"
text = "#ebdbb2"
accent = "#458588"
warn = "#d79921"
err = "#cc241d"

[character]
success_symbol = "[➜](accent) "
error_symbol = "[✗](err) "

[cmd_duration]
style = "warn"

[directory]
style = "accent"

[git_branch]
style = "text"

[git_status]
style = "warn"
