palette = "pop_default"
add_newline = false
format = "$all"

[palettes.pop_default]
base = "#fffcf0"
text = "#100f0f"
accent = "#205ea6"
warn = "#ad8301"
err = "#af3029"

[character]
success_symbol = "[➜](accent) "
error_symbol = "[✗](err) "

[cmd_duration]
style = "warn"

[directory]
style = "accent"

[git_branch]
style = "text"

[git_status]
style = "warn"
