# https://raw.githubusercontent.com/catppuccin/alacritty/main/catppuccin-latte.toml

[colors.primary]
background = "#eff1f5"
foreground = "#4c4f69"
dim_foreground = "#8c8fa1"
bright_foreground = "#4c4f69"

[colors.cursor]
text = "#eff1f5"
cursor = "#dc8a78"

[colors.vi_mode_cursor]
text = "#eff1f5"
cursor = "#7287fd"

[colors.search.matches]
foreground = "#4c4f69"
background = "#eff1f5"

[colors.search.focused_match]
foreground = "#4c4f69"
background = "#eff1f5"

[colors.footer_bar]
foreground = "#4c4f69"
background = "#eff1f5"

[colors.hints.start]
foreground = "#4c4f69"
background = "#eff1f5"

[colors.hints.end]
foreground = "#4c4f69"
background = "#eff1f5"

[colors.selection]
text = "#eff1f5"
background = "#eff1f5"

[colors.normal]
black = "#e6e9ef"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#5c5f77"

[colors.bright]
black = "#acb0be"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#6c6f85"

[[colors.indexed_colors]]
index = 16
color = "#fe640b"

[[colors.indexed_colors]]
index = 17
color = "#dc8a78"
