palette = "pop_default"
add_newline = false
format = "$all"

[palettes.pop_default]
base = "#eff1f5"
text = "#4c4f69"
accent = "#1e66f5"
warn = "#df8e1d"
err = "#d20f39"

[character]
success_symbol = "[➜](accent) "
error_symbol = "[✗](err) "

[cmd_duration]
style = "warn"

[directory]
style = "accent"

[git_branch]
style = "text"

[git_status]
style = "warn"
