palette = "pop_default"
add_newline = false
format = "$all"

[palettes.pop_default]
base = "#1f1f28"
text = "#dcd7ba"
accent = "#7e9cd8"
warn = "#dca561"
err = "#c34043"

[character]
success_symbol = "[➜](accent) "
error_symbol = "[✗](err) "

[cmd_duration]
style = "warn"

[directory]
style = "accent"

[git_branch]
style = "text"

[git_status]
style = "warn"
