[colors.primary]
foreground = "#575279"
background = "#faf4ed"
dim_foreground = "#797593"
bright_foreground = "#575279"

[colors.cursor]
text = "#575279"
cursor = "#cecacd"

[colors.vi_mode_cursor]
text = "#575279"
cursor = "#cecacd"

[colors.search.matches]
foreground = "#575279"
background = "#faf4ed"

[colors.search.focused_match]
foreground = "#575279"
background = "#faf4ed"

[colors.hints.start]
foreground = "#575279"
background = "#faf4ed"

[colors.hints.end]
foreground = "#575279"
background = "#faf4ed"

[colors.line_indicator]
foreground = "#575279"
background = "#faf4ed"

[colors.footer_bar]
foreground = "#575279"
background = "#faf4ed"

[colors.selection]
text = "#575279"
background = "#faf4ed"

[colors.normal]
black = "#f2e9e1"
red = "#b4637a"
green = "#286983"
yellow = "#ea9d34"
blue = "#56949f"
magenta = "#907aa9"
cyan = "#d7827e"
white = "#575279"

[colors.bright]
black = "#9893a5"
red = "#b4637a"
green = "#286983"
yellow = "#ea9d34"
blue = "#56949f"
magenta = "#907aa9"
cyan = "#d7827e"
white = "#575279"

[colors.dim]
black = "#9893a5"
red = "#b4637a"
green = "#286983"
yellow = "#ea9d34"
blue = "#56949f"
magenta = "#907aa9"
cyan = "#d7827e"
white = "#575279"

