palette = "pop_default"
add_newline = false
format = "$all"

[palettes.pop_default]
base = "#faf4ed"
text = "#575279"
accent = "#56949f"
warn = "#ea9d34"
err = "#b4637a"

[character]
success_symbol = "[➜](accent) "
error_symbol = "[✗](err) "

[cmd_duration]
style = "warn"

[directory]
style = "accent"

[git_branch]
style = "text"

[git_status]
style = "warn"
