palette = "pop_default"
add_newline = false
format = "$all"

[palettes.pop_default]
base = "#2e3440"
text = "#eceff4"
accent = "#88c0d0"
warn = "#ebcb8b"
err = "#bf616a"

[character]
success_symbol = "[➜](accent) "
error_symbol = "[✗](err) "

[cmd_duration]
style = "warn"

[directory]
style = "accent"

[git_branch]
style = "text"

[git_status]
style = "warn"
