palette = "pop_default"
add_newline = false
format = "$all"

[palettes.pop_default]
base = "#0b0c16"
text = "#ddf7ff"
accent = "#50f7d4"
warn = "#ffd166"
err = "#ff6b6b"

[character]
success_symbol = "[➜](accent) "
error_symbol = "[✗](err) "

[cmd_duration]
style = "warn"

[directory]
style = "accent"

[git_branch]
style = "text"

[git_status]
style = "warn"
