palette = "pop_default"
add_newline = false
format = "$all"

[palettes.pop_default]
base = "#2d353b"
text = "#d3c6aa"
accent = "#7fbbb3"
warn = "#dbbc7f"
err = "#e67e80"

[character]
success_symbol = "[➜](accent) "
error_symbol = "[✗](err) "

[cmd_duration]
style = "warn"

[directory]
style = "accent"

[git_branch]
style = "text"

[git_status]
style = "warn"
