# Ansible Galaxy requirements
# Install with: ansible-galaxy install -r requirements.yml
---
collections:
  - name: community.general
    version: "9.1.0"
  - name: ansible.posix
    version: "1.6.0"





