palette = "pop_default"
add_newline = false
format = "$all"

[palettes.pop_default]
base = "#060b1e"
text = "#ffcead"
accent = "#7d82d9"
warn = "#e9bb4f"
err = "#ed5b5a"

[character]
success_symbol = "[➜](accent) "
error_symbol = "[✗](err) "

[cmd_duration]
style = "warn"

[directory]
style = "accent"

[git_branch]
style = "text"

[git_status]
style = "warn"
